# Generated by Django 5.0.4 on 2024-05-05 07:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='affidavit_vakalat_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 5, 12, 54, 37, 475893)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(default=datetime.datetime(2024, 5, 5, 12, 55, 15, 387090), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='cnr',
            field=models.CharField(default=datetime.datetime(2024, 5, 5, 12, 55, 26, 193316), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='respondent',
            field=models.CharField(default=datetime.datetime(2024, 5, 5, 12, 55, 34, 859102), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='advocate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handle_units.advocate'),
        ),
    ]
