# Generated by Django 5.0.4 on 2024-05-07 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_units', '0005_alter_team_member_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advocate_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('case_name', models.CharField(max_length=20)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handle_units.case')),
            ],
        ),
    ]
