# Generated by Django 5.0.4 on 2024-05-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_units', '0006_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='case_name',
        ),
        migrations.AlterField(
            model_name='team_member',
            name='member_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
