# Generated by Django 5.0.4 on 2024-05-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_units', '0007_remove_todo_case_name_alter_team_member_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='assign_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
