# Generated by Django 5.0.4 on 2024-05-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_units', '0008_todo_assign_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
